export default {
  AUTH_INIT: "AUTH_INIT",
  AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT_ERROR: "AUTH_LOGOUT_ERROR",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
};
