export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const UNLOAD_POSTS_SUCCESS = 'UNLOAD_POSTS_SUCCESS';
