export const LOAD_POST_ERROR = 'LOAD_POST_ERROR';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';

export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const UNLOAD_POSTS_SUCCESS = 'UNLOAD_POSTS_SUCCESS';

export const LOAD_PUBLISHED_POSTS_SUCCESS = 'LOAD_PUBLISHED_POSTS_SUCCESS';
export const UNLOAD_PUBLISHED_POSTS_SUCCESS = 'UNLOAD_PUBLISHED_POSTS_SUCCESS';
