export const AUTH_INIT = "AUTH_INIT";

export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
