export const LOAD_PUBLISHED_POSTS_SUCCESS = 'LOAD_PUBLISHED_POSTS_SUCCESS';
export const LOAD_MORE_PUBLISHED_POSTS_SUCCESS = 'LOAD_MORE_PUBLISHED_POSTS_SUCCESS';
export const UNLOAD_PUBLISHED_POSTS_SUCCESS = 'UNLOAD_PUBLISHED_POSTS_SUCCESS';
export const LAST_PAGE_PUBLISHED_POSTS = 'LAST_PAGE_PUBLISHED_POSTS';
